### ISSUE TITLE
Separate config for line-continuation indentation

### ISSUE THREAD

**Issue by jaymzh** [turboladen/tailor#102]
See https://github.com/turboladen/tailor/issues/92#issuecomment-5234608 for context, but I'd like line-continuation to be able to have extra indentation.

**Comment by turboladen** [comment]
Scheduling for 1.1.0.

**Comment by jaymzh** [comment]
ping?

BTW, the docs seem to imply you can turn off this rule, but I can't see a way to turn it off other than maybe turning of 'indentation_spaces" which seems like not really what I want.

**Comment by turboladen** [comment]
Sorry about the lag in getting this fixed--I'm in the middle of a couple projects right now.  I'll try to get to this in the next couple weeks.

Could you add which part of the docs imply this?  I'd like to clear that up in the mean time.

**Comment by jaymzh** [comment]
"At this point, tailor only supports the style used in the first example. If this style isn’t to your liking, then definitely take a look at the Configurable section here to see how to turn this off." is the line that lead me looking around for the way to turn that off.

**Comment by jaymzh** [comment]
BTW, you said "scheduled for 1.1.0," but https://github.com/turboladen/tailor/blob/master/lib/tailor/version.rb shows 1.1.2...

**Comment by turboladen** [comment]
Thanks for the doc reference.

I removed from 1.1.0 because the scope for this is relatively large and I wasn't going to be able to get this in in time for that release, thus the bump.  

FWIW, I'd love to be more aggressive in getting these things implemented/fixed, but this is simply a "fun" project for me and thus doesn't get as much love as I'd like.  I have every intention in getting to them, but they take lower priority due to some other on-going work-related projects.  Please feel free to fork away...

**Comment by jaymzh** [comment]
I actually looked at the code today, but I don't know xst and most of this code is pretty opaque to me... :/

**Comment by turboladen** [comment]
Fixed in aca324e.
