### ISSUE TITLE
Rake Task now broken

### ISSUE THREAD

**Issue by miketheman** [turboladen/tailor#129]
I suspect that a result of 4230df51932510ed2c9ef43ecadd3ced4222ee2c removed the desired functionality from `Tailor::RakeTask.new` as the current behavior is to act on the tailor_opts only.
https://github.com/turboladen/tailor/blob/master/lib/tailor/rake_task.rb#L94-L96

Before, we were able to set file sets, and this is broken in 1.1.4 and 1.1.5

**Comment by turboladen** [comment]
Argh.  Thanks again for the report, @miketheman; this was definitely unintentional.  Kicking myself for not writing tests for this when I implemented it.

**Comment by miketheman** [comment]
No worries! I wondered why everything stopped working. :)

**Comment by turboladen** [comment]
It's a new feature... ;)

**Comment by turboladen** [comment]
@miketheman Any chance you could post your now-broken Rakefile?  I'd like to add test(s) for this to make sure I fix it right.

**Comment by turboladen** [comment]
Never mind, @miketheman--found one:  https://github.com/miketheman/ruby_enterprise/blob/master/Rakefile  :)

**Comment by miketheman** [comment]
Yay for open source!

**Comment by miketheman** [comment]
Interesting, and awesome.

Personally, I wonder if making the Rake Task configuration secondary to a .tailor config file is correct.

Consider:

---

I am a coder. I have my way of writing things, so I make myself a .tailorrc.

I check out a project with a Tailor RakeTask config set by the maintainer, and when tailoring my code, _MY specific config is used, not the one set by the project maintainer.

I commit code, send it to Travis, which checks for Tailor stlye via the config, and it fails.

I then scratch my head in wonderment.

---

Make sense?

**Comment by turboladen** [comment]
Yeah, totally makes sense.  I can't say that I've experienced this though, and would thus be tempted to argue that the style should live with the _project_ as opposed to the _person_, but that may be a bit close-minded on my part.  I realize there's a a bazillion different workflows out there that teams like to adopt and I don't want to impose on that.

So, take the following:

```
# .tailor
Tailor.config do |config|
  config.formatters "text"
  config.file_set 'lib/**/*.rb' do |style|
    style.max_line_length 85, level: :warn
  end

  config.file_set 'features/**/*.rb', :features do |style|
    style.max_line_length 90, level: :warn
  end
end

# Rakefile
Tailor::RakeTask do |task|
  task.formatters = "yaml"
  task.file_set 'lib/**/*.rb' do |style|
    style.max_line_length 120, level: :error
  end
end
```

When you `rake tailor`, should this result in: 
- lib/*_/_.rb uses max_line_length 120 and is an error (from Rakefile)
- features/*_/_.rb uses settings from .tailor

?

...or should lib/**/*.rb use the settings from .tailor?
...or should features/**/*.rb be ignored (since it's not in the Rakefile)?
...or in order to pull in/merge the .tailor config, should you have to specify in the Rakefile to use .tailor?

**Comment by turboladen** [comment]
Reopening until the desired functionality is agreed on.

**Comment by turboladen** [comment]
So after kicking this around a bit, I'm inclined to change this so that Rake task definitions/options override .tailor config (which I now realize what @miketheman was saying).

**Comment by miketheman** [comment]
Awesome stuff!
